---
name: Build and Push Docker Image
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  packages: write
jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }}
          --password-stdin
      - name: Set up Python and install Commitizen
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Commitizen
        run: pip install commitizen
      - name: Extract version from Commitizen
        id: get_version
        run: |
          VERSION=$(cz version --project)
          if [ -z "$VERSION" ]; then
            echo "âŒ VERSION is empty. Cannot tag Docker image."
            exit 1
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Build and push Docker image
        run: |-
          docker buildx build \
            --push \
            --tag ghcr.io/${{ github.repository }}:latest \
            --tag ghcr.io/${{ github.repository }}:${{ github.sha }} \
            --tag ghcr.io/${{ github.repository }}:${{ env.VERSION }} \
            .
